package com.mycompany.roomsreservation.entity;
// Generated 2017-04-25 17:15:42 by Hibernate Tools 4.3.1

import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Arrangements generated by hbm2java
 */
@Entity
@Table(name = "arrangements")
public class Arrangement implements java.io.Serializable {

    @Id
    @GeneratedValue
    @Column(name = "id_arrangement")
    private int idArrangement;
    @Column(name = "arrangement_name")
    private String arrangementName;
    @OneToMany(mappedBy = "arrangement")
    private List<Reservation> reservations;

    public Arrangement() {
    }

    public List<Reservation> getReservations() {
        return reservations;
    }

    public void setReservations(List<Reservation> reservations) {
        this.reservations = reservations;
    }

    public Arrangement(int idArrangement) {
        this.idArrangement = idArrangement;
    }

    public Arrangement(int idArrangement, String arrangementName) {
        this.idArrangement = idArrangement;
        this.arrangementName = arrangementName;
    }

    public int getIdArrangement() {
        return this.idArrangement;
    }

    public void setIdArrangement(int idArrangement) {
        this.idArrangement = idArrangement;
    }

    public String getArrangementName() {
        return this.arrangementName;
    }

    public void setArrangementName(String arrangementName) {
        this.arrangementName = arrangementName;
    }

}
