package com.mycompany.roomsreservation.entity;
// Generated 2017-04-25 17:15:42 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;

/**
 * Reservations generated by hbm2java
 */
@Entity
@Table(name = "reservations")
public class Reservation implements java.io.Serializable {

    @Id
    @GeneratedValue
    @Column(name = "id_reservation")
    private int idReservation;
    @Column(name = "full_name")
    private String fullName;
    @Column(name = "email")
    private String email;
    @Temporal(javax.persistence.TemporalType.DATE)
    @Column(name = "start_date")
    private Date startDate;
    @Temporal(javax.persistence.TemporalType.DATE)
    @Column(name = "end_date")
    private Date endDate;
    @Column(name = "if_accepted")
    private Boolean ifAccepted;
    @Column(name = "company")
    private String company;
    @ManyToOne
    @JoinColumn(name = "id_room")
    private Room room;
    @ManyToOne
    @JoinColumn(name = "id_arrangement")
    private Arrangement arrangement;

    public Reservation() {
    }

    public Reservation(int idReservation) {
        this.idReservation = idReservation;
    }

    public Reservation(int idReservation, String fullName, String email, Date startDate, Date endDate, Boolean ifAccepted, String company, Room room, Arrangement arrangement) {
        this.idReservation = idReservation;
        this.fullName = fullName;
        this.email = email;
        this.startDate = startDate;
        this.endDate = endDate;
        this.ifAccepted = ifAccepted;
        this.company = company;
        this.room = room;
        this.arrangement = arrangement;
    }

    public int getIdReservation() {
        return this.idReservation;
    }

    public void setIdReservation(int idReservation) {
        this.idReservation = idReservation;
    }

    public String getFullName() {
        return this.fullName;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Date getStartDate() {
        return this.startDate;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    public Date getEndDate() {
        return this.endDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    public Boolean getIfAccepted() {
        return this.ifAccepted;
    }

    public void setIfAccepted(Boolean ifAccepted) {
        this.ifAccepted = ifAccepted;
    }

    public String getCompany() {
        return this.company;
    }

    public void setCompany(String company) {
        this.company = company;
    }

    public Room getRoom() {
        return room;
    }

    public void setRoom(Room room) {
        this.room = room;
    }

    public Arrangement getArrangement() {
        return arrangement;
    }

    public void setArrangement(Arrangement arrangement) {
        this.arrangement = arrangement;
    }

}
